ci:
  autoupdate_schedule: weekly

# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 0.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/pycqa/isort
    rev: 0.0.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 0.0.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/keewis/blackdoc
    rev: 0.0.0
    hooks:
      - id: blackdoc
        additional_dependencies: ["black==0.0.0"]
      - id: blackdoc-autoupdate-black
  - repo: https://github.com/pycqa/flake8
    rev: 0.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/kynan/nbstripout
    rev: 0.0.0
    hooks:
      - id: nbstripout
        args: [--extra-keys=metadata.kernelspec metadata.language_info.version]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 0.0.0
    hooks:
      - id: prettier
